config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'home#dashboard'
  resources :movies
  post "import_csv" => "home#import_csv"
  get "import_csv_form" => "home#import_csv_form"
end

app/models/actor.rb
class Actor < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
	validates_uniqueness_of :name, :case_sensitive => false
	has_many :locations
end

app/models/director.rb
class Director < User
end

app/models/location.rb
class Location < ApplicationRecord
	validates_uniqueness_of :name, :case_sensitive => false
	has_many :shoot_locations
	belongs_to :country
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_casts
	has_many :reviews
	has_many :actor, through: :movie_casts
	has_many :shoot_locations, through: :movie_casts
	belongs_to :director

	def self.list(options = {})
		conditions = []
		conditions << "actors_movie_casts.id = '#{options[:actor_id]}'" if options[:actor_id].present?
		Movie.joins(:director
			).joins(:movie_casts => :actor
			).group("movie_id"
			).select("movies.id, movies.name, movies.description, movies.year, 
								movies.avg_rating, users.name as director_name, 
								group_concat(actors_movie_casts.name) as actors_name"
			).where(conditions.join(" AND ")).order("avg_rating desc")
	end
end

app/models/movie_cast.rb
class MovieCast < ApplicationRecord
	belongs_to :actor
	belongs_to :movie
	has_many :shoot_locations
end

app/models/person.rb
class Person < User
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/shoot_location.rb
class ShootLocation < ApplicationRecord
	belongs_to :location
	belongs_to :movie_cast
end

app/models/user.rb
class User < ApplicationRecord
	validates_uniqueness_of :name, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'import_csv_data.rb'
class HomeController < ApplicationController
	def dashboard		
	end

	def import_csv_form
		
	end

	def import_csv
		if params[:type].present? && params[:file].present?
			ImportCsvData.import_movies(params[:file]) if params[:type] == "Movie"
			ImportCsvData.import_movies(params[:file]) if params[:type] == "Review"
			redirect_to root_path, notice: 'File processed successfully.'
		else
			redirect_to root_path, notice: 'Something Went wrong.'
		end
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.list({actor_id: params[:actor_id]})
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/dashboard.html.erb
<p>
  <%=  link_to "Import Movie Csv", import_csv_form_path(type: "Movie")%> <br>  
  <%=  link_to "Import Review Csv", import_csv_form_path(type: "Review")%> <br>  
  <%=  link_to "Movie List", movies_path%>
</p>

app/views/home/import_csv_form.html.erb
<%= form_with url: import_csv_path(type: params[:type]), method: "post", local: true, class: "form-inline" do |form| %>
<div class="col">
  <%= form.file_field :file, class: "form-control", placeholder: "Upload file" %>
</div>
<div class="col">
  <%= form.submit "Import CSV", class: "btn btn-outline-danger" %>
</div>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<%=  link_to "Home Page", root_path%>

<%= form_with url: movies_path, method: "get", local: true, class: "form-inline" do |form| %>
<div>
  <%= form.select :actor_id, Actor.all.map {|p| [ p.name, p.id ] }, {:include_blank => 'All Actor', :selected => params[:actor_id] }, class: "form-control" %>
  <%= form.submit "Search", class: "btn btn-outline-danger" %>
</div>
<% end -%>

<% if @movies.present? %>
  <table class="table table-striped custom-table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Avg Rating</th>
        <th>Description</th>
        <th>Year</th>
        <th>Actors</th>
        <th>Director</th>
      </tr>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.id %></td>
          <td><%= movie.name %></td>
          <td><%= movie.avg_rating %></td>
          <td><%= movie.description %></td>
          <td><%= movie.year %></td>
          <td><%= movie.actors_name %></td>
          <td><%= movie.director_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <%= "No Movie Present" %>
<% end %>